[package]
name = "rssg"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.13"
clap = "4"
dialoguer = "0.12"
serde = { version = "1", features = ["derive"] }
toml = "1"
tiny_http = "0.12"
syntect = "5"
